server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: userService
          uri: http://localhost:8080/
          predicates:
            - Path=/api/user/**
        - id: boxService
          uri: http://localhost:8082/
          predicates:
            - Path=/api/boxms/**
        - id: reservationService
          uri: http://localhost:8083/
          predicates:
            - Path=/api/reservationms/**